const { analyzeMedicalCredential } = require('../services/mlService');
const { initiatePayout } = require('../services/squadService');
const { Verification, Payouts, Practitioner, Sequelize, User } = require('../models');
const sequelize = require('../config/database');
const { Op } = require('sequelize');

/**
 * Step 1: Admin-Driven Practitioner Creation
 * Restricted to Admin users only.
 */
const calculateBaseAmount = (specialty, years) => {
    const rates = { 
        'Surgeon': 1500000, 
        'Cardiologist': 1200000, 
        'General Practitioner': 500000, 
        'Nurse': 400000 
    };
    const base = rates[specialty] || 5000;
    const multiplier = 1 + Math.min((years * 0.05), 1.0); 
    return Math.floor(base * multiplier);
};

exports.submitCredentials = async (req, res) => {
    try {
        // SECURITY: Ensure the requester is actually the Admin
        if (req.user.role !== 'admin') {
            return res.status(403).json({ success: false, error: "Unauthorized." });
        }

        const { 
            fullName,
            email, 
            mdcnNumber, 
            specialty, 
            yearsOfPractice, 
        } = req.body;

        if (!req.files || !req.files['mdcnCertificate'] || !req.files['governmentId']) {
            return res.status(400).json({ 
                success: false, 
                message: "Both MDCN Certificate and Government ID are required." 
            });
        }

        const mdcnCertificatePath = req.files['mdcnCertificate'][0].path;
        const governmentIdPath = req.files['governmentId'][0].path;

        // 1. Logic: Determine the 'Locked' Disbursement Amount
        const assignedAmount = calculateBaseAmount(specialty, yearsOfPractice || 0);

        // 2. Database Creation (ID is auto-generated by the DB)
        const practitioner = await Practitioner.create({
            fullName,
            email,
            licenseNumber: mdcnNumber,
            specialty: specialty || 'General Practitioner',
            yearsOfPractice: yearsOfPractice || 0,
            bankCode: null,
            accountNumber: null,
            accountName: null,
            amount: assignedAmount, // Ensure 'amount' exists in your Practitioner model
            documentPath: mdcnCertificatePath,   // Locked into DB for the ML engine to read
            governmentIdPath: governmentIdPath,
            isVerified: false,
            isActive: true
        }); // <--- This was missing!

        // 3. Response: Return the auto-generated Practitioner ID
        res.status(201).json({
            success: true,
            message: "Practitioner record initialized successfully.",
            data: {
                practitionerId: practitioner.id, // This is the auto-generated ID
                lockedAmount: assignedAmount
            }
        });

    } catch (error) {
        console.error("Creation Error:", error.message);
        // Handle case where licenseNumber is already in use
        if (error.name === 'SequelizeUniqueConstraintError') {
            return res.status(400).json({ success: false, error: "This MDCN number is already registered." });
        }
        res.status(500).json({ success: false, error: error.message });
    }
};

exports.processVerificationML = async (req, res) => {
    try {
        const { practitionerId, licenseNumber } = req.body;

        if (!practitionerId) {
            return res.status(400).json({ success: false, message: "Practitioner ID is required." });
        }

        // 2. FETCH THE PRACTITIONER FIRST (This fixes the initialization crash)
        const practitioner = await Practitioner.findByPk(practitionerId);
        if (!practitioner) {
            return res.status(404).json({ success: false, message: "Practitioner not found." });
        }

        // 3. Extract data from the fetched practitioner instance
        const cleanLicense = practitioner.licenseNumber.trim().toUpperCase();
        const documentPath = practitioner.documentPath; 
        const govIdPath = practitioner.governmentIdPath; 

        // 4. Validate the license number format retrieved from the database
        const licenseRegex = /^(MDN|MDCN)\/[A-Z0-9\/_-]+$/i;
        if (!licenseRegex.test(cleanLicense)) {
            return res.status(400).json({ success: false, message: "Invalid MDCN format (e.g., MDCN/12345)." });
        }

        // 5. Ensure files were successfully captured in Step 1
        if (!documentPath) {
            return res.status(400).json({ 
                success: false, 
                message: "No document found for this practitioner. Please upload it in Step 1." 
            });
        }

        // 6. Duplicate Check: Ensure no OTHER practitioner is using this license number
        const licenseInUse = await Practitioner.findOne({ 
            where: { 
                licenseNumber: cleanLicense, 
                id: { [Op.ne]: practitionerId } 
            } 
        });
        if (licenseInUse) {
            return res.status(400).json({ success: false, message: "License already linked to another account." });
        }
        
        // Call the AI Service (even if it returns 0, we log it for the demo)
        const aiResult = await analyzeMedicalCredential(
            practitioner.documentPath, 
            practitioner.governmentIdPath, 
            practitioner
        );

        let status;
        let message;
        let triggerPayment = false;
        const score = aiResult.trust_score;

        if (score > 70) {
            status = 'APPROVED';
            message = "Practitioner verified as Legit. Onboarding/Payment authorized.";
            triggerPayment = true;
        } else if (score >= 30) {
            status = 'UNDER_REVIEW';
            message = "Credentials flagged for manual audit. Onboarding paused.";
        } else {
            status = 'BLOCKED';
            message = "Extreme fraud risk detected. Account suspended and reported to MDCN.";
        }

        // 5. DATABASE UPDATES (Audit Trail)
        // Record the verification attempt
        const verification = await Verification.create({
            practitioner_id: practitioner.id,
            document_url: documentPath,
            trust_score: score,
            ml_flags: aiResult.ml_flags,
            status: status
        });

        if (status === 'BLOCKED') {
            await practitioner.update({ 
                isActive: false, 
                isVerified: false 
            });
            const mlFlags = aiResult.ml_flags || [];

            const primaryReason = mlFlags.length > 0 
                ? mlFlags.join(', ') 
                : "Low Trust Score";

            console.log(`\x1b[41m%s\x1b[0m`, `[SECURITY ALERT] Account Deactivated.`);
            console.log(`\x1b[33m%s\x1b[0m`, `Reason: ${primaryReason}`);
            console.log(`\x1b[33m%s\x1b[0m`, `License: ${licenseNumber} | ID: ${practitionerId}`);
            console.log(`\x1b[41m%s\x1b[0m`, `[FRAUD ALERT] MDCN Report generated for License: ${licenseNumber}`);
        }

        return res.status(200).json({
            success: true,
            status,
            message,
            data: {
                trustScore: score,
                flags: aiResult.ml_flags,
                verificationId: verification.id
            }
        });
    } catch (error) {
        // 1. Print this to your local terminal console so you can read the real stack trace
        console.error("❌ ACTUAL ML VERIFICATION CRASH ERROR:", error);

        // 2. Return the real message to Postman so you don't have to guess
        res.status(500).json({ 
            success: false, 
            error: "AI Service Interruption",
            details: error.message 
        });
    }
};

exports.processVerificationBypass = async (req, res) => {
    const { practitionerId, licenseNumber } = req.body;

    try {
        // 1. Initial Validations
        if (!licenseNumber || !practitionerId) {
            return res.status(400).json({ success: false, message: "Practitioner ID and License Number are required." });
        }

        const cleanLicense = licenseNumber.trim().toUpperCase();
        const licenseRegex = /^(MDN|MDCN)\/[A-Z0-9\/_-]+$/i;
        if (!licenseRegex.test(cleanLicense)) {
            return res.status(400).json({ success: false, message: "Invalid MDCN format (e.g., MDCN/12345)." });
        }

        // Fetch the profile initialized in Step 1
        const practitioner = await Practitioner.findByPk(practitionerId);
        if (!practitioner) return res.status(404).json({ success: false, message: "Practitioner not found." });

        // 🛡️ FIX 1: Look inside the Practitioner model table instead of User
        const licenseInUse = await Practitioner.findOne({ 
            where: { licenseNumber: cleanLicense, id: { [Op.ne]: practitionerId } } 
        });
        if (licenseInUse) {
            return res.status(400).json({ success: false, message: "License already linked to another account." });
        }
        
        // 2. Build the simulated approval verification log
        const verification = await Verification.create({
            practitioner_id: practitioner.id,
            document_url: practitioner.documentPath || 'https://placeholder.com/bypass-active.pdf',
            status: 'APPROVED', 
            trust_score: 100,
            // 🛡️ FIX 2: Stringify the payload object so your DB column doesn't choke
            ml_flags: JSON.stringify({ bypass: true, demo_mode: true })
        });

        // 🛡️ FIX 3: Update the Practitioner lifecycle state so the payout system clears them
        await practitioner.update({ 
            licenseNumber: cleanLicense,
            isVerified: true,
            isActive: true 
        });

        // Diagnostic verification success tracking log
        console.log(`\x1b[42m%s\x1b[0m`, `[DEMO BYPASS] Practitioner ${practitioner.fullName} successfully fast-tracked to APPROVED.`);

        return res.status(201).json({
            success: true,
            message: "Bypass successful. Practitioner approved for onboarding and payouts.",
            verificationId: verification.id,
            status: "APPROVED",
            trustScore: 100
        });

    } catch (error) {
        console.error(" Bypass Controller Processing Fault:", error.message);
        res.status(500).json({ success: false, error: error.message });
    }
};

exports.executeStep3Payout = async (req, res) => {
    const { verificationId } = req.body; // Only need the ID to trigger the flow
    const t = await sequelize.transaction();

    try {
        // 1. Fetch Records (Include Practitioner to get the base_amount)
        const verification = await Verification.findByPk(verificationId, { 
            include: [{ model: Practitioner }] 
        });

        if (!verification) return res.status(404).json({ message: "Verification ID invalid." });
        
        const practitioner = verification.practitioner;
        if (!practitioner) {
            await t.rollback();
            return res.status(404).json({ success: false, message: "Associated practitioner profile missing." });
        }

        if (verification.status !== 'APPROVED' || !practitioner.isVerified || !practitioner.isActive) {
            await t.rollback();
            return res.status(403).json({ 
                success: false, 
                message: `Disbursement rejected. Current Verification Status: [${verification.status}]. Core profile must be APPROVED.` 
            });
        }
        
        // SECURITY: Pull the amount assigned by the backend during Signup
        const payoutAmount = practitioner.amount; // Extracted safely from DB state
        if (!payoutAmount || payoutAmount <= 0) {
            await t.rollback();
            return res.status(400).json({ success: false, message: "Invalid backend distribution amount configuration." });
        }

        // --- SQUAD SEQUENCE ---

        // 2. INITIATE
        const initiation = await initiatePayout({
            amount: Number(amount),
            bankCode: practitioner.bankCode,
            accountNumber: practitioner.accountNumber,
            accountName: practitioner.accountName || practitioner.fullName, // if you have it
            practitionerId: practitioner.id,
            licenseNumber: practitioner.licenseNumber,
            transaction_ref: transaction_ref
        });
        if (!initiation.success) throw new Error("Squad Initiation Failed");

        // 3. LOOKUP
        const lookup = await lookupAccount(practitioner.bankCode, practitioner.accountNumber);
        if (!lookup.success) throw new Error(`Bank Lookup Failed: ${lookup.error}`);

        // 4. EXECUTE
        const payoutResponse = await executePayout({
            amount: payoutAmount,
            bankCode: practitioner.bankCode,
            accountNumber: practitioner.accountNumber,
            licenseNumber: practitioner.licenseNumber,
            practitionerId: practitioner.id
        });
        if (!payoutResponse.success) throw new Error("Fund Transfer Failed");

        // --- DATABASE SYNC ---

        // 5. Update Statuses & Create Ledger
        await verification.update({ status: 'APPROVED' }, { transaction: t });
        await practitioner.update({ isVerified: true }, { transaction: t });

        const payoutRecord = await Payouts.create({
            verification_id: verification.id,
            squad_transaction_ref: payoutResponse.data.transaction_reference,
            amount: payoutAmount,
            status: 'SUCCESS'
        }, { transaction: t });

        await t.commit();

        return res.status(200).json({
            success: true,
            message: "Disbursement finalized.",
            data: {
                amountPaid: payoutAmount,
                recipient: lookup.data.account_name,
                transactionRef: payoutRecord.squad_transaction_ref
            }
        });

    } catch (error) {
        await t.rollback();
        console.error('Payout Finalization Failure:', error.message);
        return res.status(500).json({ success: false, error: error.message });
    }
};
exports.processVerification = async (req, res) => {
    const { practitionerId, licenseNumber } = req.body;

    try {
        // 1. Verify Practitioner exists
        const practitioner = await Practitioner.findByPk(practitionerId);
        if (!practitioner) return res.status(404).json({ message: "Practitioner not found" });

        // 2. Check if a verification record already exists to avoid duplicates
        let verification = await Verification.findOne({ where: { practitioner_id: practitionerId } });

        if (verification) {
            return res.status(400).json({ 
                message: "Verification already in progress or completed.",
                verificationId: verification.id 
            });
        }

        // 3. Create the Verification "Paper Trail"
        verification = await Verification.create({
            practitioner_id: practitioner.id,
            document_url: 'https://placeholder.com/demo-license.pdf', // Hardcoded for hackathon
            status: 'UNDER_REVIEW', // Step 2 puts it in review
            trust_score: 100,
            ml_flags: { bypass: true, reason: 'Hackathon Demo' }
        });

        // 4. Update the Practitioner's license number in their profile
        await practitioner.update({ licenseNumber });

        return res.status(201).json({
            success: true,
            message: "Verification initialized. Proceed to payment (Step 3).",
            verificationId: verification.id
        });

    } catch (error) {
        console.error('Verification Error:', error.message);
        res.status(500).json({ success: false, error: error.message });
    }
};

exports.initiateManualPayout = async (req, res) => {
    const { practitionerId, amount, transaction_ref } = req.body;

    try {
        if (!practitionerId || !amount || Number(amount) <= 0) {
            return res.status(400).json({
                success: false,
                message: "Valid practitionerId and amount (> 0) are required."
            });
        }

        const practitioner = await Practitioner.findByPk(practitionerId);
        
        if (!practitioner || !practitioner.isVerified) {
            return res.status(403).json({ 
                success: false, 
                message: "Payout Blocked: Practitioner must be 'Verified'." 
            });
        }

        if (!practitioner.bankCode || !practitioner.accountNumber) {
            return res.status(400).json({
                success: false,
                message: "Practitioner bank details are incomplete."
            });
        }

        const squadResponse = await initiatePayout({
            amount: Number(amount),
            bankCode: practitioner.bankCode,
            accountNumber: practitioner.accountNumber,
            accountName: practitioner.accountName || practitioner.fullName, // if you have it
            practitionerId: practitioner.id,
            licenseNumber: practitioner.licenseNumber,
            transaction_ref: transaction_ref
        });

        if (squadResponse.success) {
            const payout = await Payouts.create({
                practitioner_id: practitioner.id,
                squad_transaction_ref: squadResponse.data?.transaction_reference,
                amount: Number(amount),
                status: 'PENDING',
                verification_id: null
            });

            return res.status(200).json({
                success: true,
                message: "Manual payout initiated successfully",
                data: {
                    payout_id: payout.id,
                    transaction_reference: squadResponse.data?.transaction_reference,
                    ...squadResponse.data
                }
            });
        } else {
            console.error("Squad API Error:", squadResponse.squadError || squadResponse);

            return res.status(400).json({ 
                success: false, 
                message: squadResponse.message,
                squadDetails: process.env.NODE_ENV === 'development' ? squadResponse.squadError : undefined
            });
        }
    } catch (error) {
        console.error("Initiate Manual Payout Error:", error);
        res.status(500).json({ 
            success: false, 
            message: "Internal server error",
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
};